CREATE TABLE IF NOT EXISTS users(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS sqrl(
  -- idk, suk, and vuk are all 256 bit values
  -- Postgres does not index bytea data types
  -- therefore using base64url encoded values
  idk CHAR(43) PRIMARY KEY,
  suk CHAR(43),
  vuk CHAR(43),
  -- When created
  created TIMESTAMP DEFAULT NOW(),
  -- when disabled last
  disabled TIMESTAMP,
  -- when superseded last
  superseded TIMESTAMP,
  user_id INT NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS nuts(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initial INT REFERENCES nuts(id),
  ip INET NOT NULL,
  hmac CHAR(45),
  -- When nut was created
  created TIMESTAMP DEFAULT NOW(),
  -- this nut has been used
  used TIMESTAMP,
  -- user completed successful authentication
  identified TIMESTAMP,
  -- User issued credentials
  issued TIMESTAMP,
  user_id INT REFERENCES users(id)
);
