CREATE TABLE IF NOT EXISTS users(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS sqrl(
  idk CHAR(44) PRIMARY KEY,
  suk CHAR(44),
  vuk CHAR(44),
  -- When created
  created TIMESTAMP DEFAULT NOW(),
  -- when disabled last
  disabled TIMESTAMP,
  -- when superseded last
  superseded TIMESTAMP,
  user_id INT NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS nuts(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initial INT REFERENCES nuts(id),
  nut CHAR(44) NOT NULL ,
  ip VARCHAR(50) NOT NULL,
  hmac CHAR(45),
  -- When nut was created
  created TIMESTAMP DEFAULT NOW(),
  -- this nut has been used
  used TIMESTAMP,
  -- user completed successful authentication
  identified TIMESTAMP,
  -- User issued credentials
  issued TIMESTAMP,
  user_id INT REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS nuts_nut ON nuts (nut);
